Repository team-haribo/GOMS-Backend-V2, pull requests merged in 2023-07, with the labels that each got.

#3 🔀 :: pull request 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 3️⃣ Priority: Low, 📃 Docs

#5 🔀 :: Account 애그리거트 추가 및 Jpa 세팅
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependenciesVersions.kt
  buildSrc/src/main/kotlin/PluginVersions.kt
  goms-application/build.gradle.kts
  goms-application/src/test/kotlin/com/goms/v2/GomsApplicationTests.kt
  goms-domain/src/main/kotlin/com/goms/v2/common/annotation/Aggregate.kt
  goms-domain/src/main/kotlin/com/goms/v2/common/annotation/RootAggregate.kt
  goms-domain/src/main/kotlin/com/goms/v2/domain/.gitkeep
  goms-domain/src/main/kotlin/com/goms/v2/domain/account/Account.kt
  goms-domain/src/main/kotlin/com/goms/v2/domain/account/Authority.kt
  goms-domain/src/main/kotlin/com/goms/v2/domain/account/StudentNumber.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/AccountRepository.kt
  goms-infrastructure/build.gradle.kts
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/BaseIdxEntity.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/BaseUUIDEntity.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/entity/AccountJpaEntity.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/entity/StudentNumberEntity.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/mapper/AccountMapper.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/repository/AccountJpaRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/repository/AccountRepositoryImpl.kt
  goms-infrastructure/src/main/resources/application-local.yml
  goms-infrastructure/src/main/resources/application-prod.yml
  goms-infrastructure/src/main/resources/application.properties
  goms-presentation/build.gradle.kts
  goms-presentation/src/test/kotlin/com/goms/v2/GomsPresentationApplicationTests.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#7 🔀 :: gitkeep 추가
  goms-application/src/main/kotlin/com/goms/v2/.gitkeep
  goms-application/src/test/kotlin/com/goms/v2/.gitkeep
  goms-presentation/src/main/kotlin/com/goms/v2/.gitkeep
  goms-presentation/src/test/kotlin/com/goms/v2/.gitkeep
Labels: 3️⃣ Priority: Low

#11 🔀 :: Exception 설정 추가
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/.gitkeep
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/exception/ErrorCode.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/exception/exception/GomsException.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/exception/handler/GlobalExceptionHandler.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/exception/response/ErrorResponse.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#12 🔀 :: SpringSecurity 관련 설정
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependenciesVersions.kt
  goms-domain/src/main/kotlin/com/goms/v2/domain/account/Authority.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/AccountRepository.kt
  goms-infrastructure/build.gradle.kts
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/config/PropertiesScanConfig.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/exception/ErrorCode.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/filter/ExceptionHandlerFilter.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/filter/JwtRequestFilter.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/filter/RequestLogFilter.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/filter/config/FilterConfig.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/SecurityConfig.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/handler/CustomAccessDeniedHandler.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/handler/CustomAuthenticationEntryPoint.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/JwtParser.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/common/exception/ExpiredRefreshTokenException.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/common/exception/InvalidTokenException.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/common/exception/InvalidTokenTypeException.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/common/properties/JwtExpTimeProperties.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/common/properties/JwtProperties.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/principal/StudentCouncilDetails.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/principal/StudentCouncilDetailsService.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/principal/StudentDetails.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/principal/StudentDetailsService.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/mapper/AccountMapper.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/repository/AccountRepositoryImpl.kt
  goms-infrastructure/src/main/resources/application-local.yml
Labels: 2️⃣ Priority: Medium, ✨ Feature

#15 🔀 :: Exception 처리를 application 단에서 처리할 수 있도록 변경
  goms-application/src/main/kotlin/com/goms/v2/global/.gitkeep
  goms-application/src/main/kotlin/com/goms/v2/global/exception/ErrorCode.kt
  goms-application/src/main/kotlin/com/goms/v2/global/exception/exception/GomsException.kt
  goms-application/src/main/kotlin/com/goms/v2/global/exception/handler/GlobalExceptionHandler.kt
  goms-application/src/main/kotlin/com/goms/v2/global/exception/response/ErrorResponse.kt
  goms-infrastructure/build.gradle.kts
Labels: 2️⃣ Priority: Medium, 🔨 코드 리팩터링
