Repository team-haribo/GOMS-Backend-V2, pull requests merged in 2023-08, with the labels that each got.

#13 🔀 :: gauth 로그인 기능 구현
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependenciesVersions.kt
  goms-application/build.gradle.kts
  goms-application/src/main/kotlin/com/goms/v2/common/annotation/UseCaseWithTransaction.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/dto/GAuthExceptionDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/dto/GAuthTokenDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/dto/GAuthUserInfoDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/dto/request/SignInDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/dto/response/TokenDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/exception/ExpiredCodeException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/exception/InternalServerErrorException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/exception/SecretMismatchException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/exception/ServiceNotFoundException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/spi/GAuthPort.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/spi/TokenPort.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/SignInUseCase.kt
  goms-application/src/main/kotlin/com/goms/v2/gloabl/.gitkeep
  goms-application/src/main/kotlin/com/goms/v2/gloabl/event/SaveRefreshTokenEvent.kt
  goms-application/src/main/kotlin/com/goms/v2/gloabl/exception/ErrorCode.kt
  goms-application/src/main/kotlin/com/goms/v2/gloabl/exception/exception/GomsException.kt
  goms-application/src/main/kotlin/com/goms/v2/gloabl/exception/handler/GlobalExceptionHandler.kt
  goms-application/src/main/kotlin/com/goms/v2/gloabl/exception/response/ErrorResponse.kt
  goms-application/src/main/kotlin/com/goms/v2/global/.gitkeep
  goms-application/src/main/kotlin/com/goms/v2/global/exception/exception/GomsException.kt
  goms-domain/build.gradle.kts
  goms-domain/src/main/kotlin/com/goms/v2/domain/auth/RefreshToken.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/account/AccountRepository.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/auth/RefreshTokenRepository.kt
  goms-infrastructure/build.gradle.kts
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/.gitkeep
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/config/ComponentScanConfig.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/config/PropertiesScanConfig.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/event/SaveRefreshTokenEventHandler.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/filter/ExceptionHandlerFilter.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/handler/CustomAccessDeniedHandler.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/GenerateTokenAdapter.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/common/exception/ExpiredRefreshTokenException.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/common/exception/InvalidTokenException.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/common/exception/InvalidTokenTypeException.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/principal/StudentCouncilDetailsService.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/principal/StudentDetailsService.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/mapper/AccountMapper.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/repository/AccountJpaRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/repository/AccountRepositoryImpl.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/auth/entity/RefreshTokenJpaEntity.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/auth/mapper/GAuthDataMapper.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/auth/mapper/RefreshTokenMapper.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/auth/repository/RefreshTokenJpaRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/auth/repository/RefreshTokenRepositoryImpl.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/gauth/GAuthAdapter.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/gauth/config/GAuthConfig.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/gauth/property/GAuthProperties.kt
  goms-infrastructure/src/main/resources/application-local.yml
  goms-presentation/build.gradle.kts
  goms-presentation/src/main/kotlin/com/goms/v2/domain/auth/AuthController.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/auth/dto/request/SignInHttpRequest.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/auth/dto/response/TokenHttpResponse.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/auth/mapper/AuthDataMapper.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#17 🔀 :: Mapper에 toDomain Mapper 추가
  goms-domain/src/main/kotlin/com/goms/v2/domain/auth/RefreshToken.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/event/SaveRefreshTokenEventHandler.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/auth/mapper/RefreshTokenMapper.kt
Labels: 1️⃣ Priority: High, 😈 버그 fix

#19 🔀 :: CI 작성
  .github/workflows/CI.yml
Labels: 2️⃣ Priority: Medium, ✨ Feature

#22 🔀 :: 토큰 재발급 기능 추가
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/data/dto/GAuthTokenDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/data/dto/GAuthUserInfoDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/data/dto/SignInDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/data/dto/TokenDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/data/event/SaveRefreshTokenEvent.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/data/event/SaveRefreshTokenEventHandler.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/dto/GAuthExceptionDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/exception/AccountNotFoundException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/exception/ExpiredGAuthCodeException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/exception/ExpiredRefreshTokenException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/exception/GAuthSecretMismatchException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/exception/GAuthServiceNotFoundException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/exception/InvalidTokenTypeException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/spi/GAuthPort.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/spi/TokenParserPort.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/spi/TokenPort.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/ReissueTokenUseCase.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/SignInUseCase.kt
  goms-domain/src/main/kotlin/com/goms/v2/domain/auth/RefreshToken.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/auth/RefreshTokenRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/GenerateTokenAdapter.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/TokenParserAdapter.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/auth/mapper/GAuthDataMapper.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/auth/mapper/RefreshTokenMapper.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/auth/repository/RefreshTokenRepositoryImpl.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/gauth/GAuthAdapter.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/auth/AuthController.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/auth/mapper/AuthDataMapper.kt
  goms-presentation/src/test/kotlin/com/goms/v2/common/AnyValueObjectGenerator.kt
  goms-presentation/src/test/kotlin/com/goms/v2/domain/.gitkeep
  goms-presentation/src/test/kotlin/com/goms/v2/domain/auth/ReissueTokenUseCaseTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#24 🔀 :: GAuth 로그인 에러 고치기
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/data/dto/GAuthUserInfoDto.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/gauth/GAuthAdapter.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/gauth/mapper/GAuthDataMapper.kt
Labels: 0️⃣ Priority: Critical, 😈 버그 fix

#25 🔀 :: QR 생성 기능 추가
  goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/.gitkeep
  goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/CreateOutingUseCase.kt
  goms-domain/src/main/kotlin/com/goms/v2/common/property/studentCouncil/OutingUUIDExpTimeProperties.kt
  goms-domain/src/main/kotlin/com/goms/v2/domain/.gitkeep
  goms-domain/src/main/kotlin/com/goms/v2/domain/studentCouncil/OutingUUID.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/studentCouncil/OutingUUIDRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/config/PropertiesScanConfig.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/studentCouncil/entity/OutingUUIDRedisEntity.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/studentCouncil/mapper/OutingUUIDMapper.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/studentCouncil/repository/OutingUUIDJpaRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/studentCouncil/repository/OutingUUIDRepositoryImpl.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilController.kt
  goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/CreateOutingUseCaseTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#27 🔀 :: 이메일 전송 기능 구현
  buildSrc/src/main/kotlin/Dependencies.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/email/data/dto/EmailDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/email/exception/EmailSendFailException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/email/exception/ManyEmailRequestException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/email/spi/EmailSendPort.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/email/usecase/SendEmailUseCase.kt
  goms-application/src/main/kotlin/com/goms/v2/gloabl/exception/ErrorCode.kt
  goms-domain/src/main/kotlin/com/goms/v2/domain/email/AuthCode.kt
  goms-domain/src/main/kotlin/com/goms/v2/domain/email/Authentication.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/account/AccountRepository.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/email/AuthCodeRepository.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/email/AuthenticationRepository.kt
  goms-infrastructure/build.gradle.kts
  goms-infrastructure/src/main/kotlin/com/goms/v2/GomsV2Application.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/config/EnableAsyncConfig.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/repository/AccountJpaRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/repository/AccountRepositoryImpl.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/email/adapter/EmailSenderAdapter.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/email/entity/AuthCodeRedisEntity.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/email/entity/AuthenticationRedisEntity.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/email/mapper/AuthCodeMapper.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/email/mapper/AuthenticationMapper.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/email/repository/AuthCodeRedisRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/email/repository/AuthCodeRepositoryImpl.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/email/repository/AuthenticationRedisRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/email/repository/AuthenticationRepositoryImpl.kt
  goms-infrastructure/src/main/resources/application-local.yml
  goms-presentation/build.gradle.kts
  goms-presentation/src/main/kotlin/com/goms/v2/domain/auth/dto/request/SignInHttpRequest.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/email/EmailAuthController.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/email/dto/request/SendEmailHttpRequest.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/email/mapper/EmailAuthDataMapper.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#29 블랙리스트 전환 기능 추가
  goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/SaveOutingBlackListUseCase.kt
  goms-domain/src/main/kotlin/com/goms/v2/domain/outing/OutingBlackList.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/outing/OutingBlackListRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/entity/OutingBlackListRedisEntity.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/mapper/OutingBlackListMapper.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingBlackListJpaRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingBlackListRepositoryImpl.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilController.kt
  goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/SaveOutingBlackListUseCaseTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature, ✅ test

#31 🔀 :: 인증번호 검증 기능 구현
  goms-application/src/main/kotlin/com/goms/v2/domain/email/exception/AuthCodeNotFoundException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/email/exception/AuthCodeNotMatchException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/email/exception/AuthenticationNotFoundException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/email/exception/TooManyAuthCodeRequestException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/email/usecase/SendEmailUseCase.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/email/usecase/VerifyAuthCodeUseCase.kt
  goms-application/src/main/kotlin/com/goms/v2/gloabl/exception/ErrorCode.kt
  goms-domain/src/main/kotlin/com/goms/v2/domain/email/Authentication.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/email/entity/AuthenticationRedisEntity.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/email/EmailAuthController.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#34 🔀 :: application 모듈에 spring web 의존성 삭제
  goms-application/build.gradle.kts
  goms-application/src/main/kotlin/com/goms/v2/common/exception/ErrorCode.kt
  goms-application/src/main/kotlin/com/goms/v2/common/exception/ErrorStatus.kt
  goms-application/src/main/kotlin/com/goms/v2/common/exception/GomsException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/exception/AccountNotFoundException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/exception/ExpiredGAuthCodeException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/exception/ExpiredRefreshTokenException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/exception/GAuthSecretMismatchException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/exception/GAuthServiceNotFoundException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/exception/InternalServerErrorException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/exception/InvalidTokenTypeException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/email/exception/AuthCodeNotFoundException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/email/exception/AuthCodeNotMatchException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/email/exception/AuthenticationNotFoundException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/email/exception/EmailSendFailException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/email/exception/ManyEmailRequestException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/email/exception/TooManyAuthCodeRequestException.kt
  goms-application/src/main/kotlin/com/goms/v2/gloabl/exception/ErrorCode.kt
  goms-application/src/main/kotlin/com/goms/v2/gloabl/exception/exception/GomsException.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/exception/handler/GlobalExceptionHandler.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/exception/response/ErrorResponse.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/filter/ExceptionHandlerFilter.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/common/exception/InvalidTokenException.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/common/exception/InvalidTokenTypeException.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/gauth/GAuthAdapter.kt
  goms-infrastructure/src/main/resources/application-local.yml
  goms-infrastructure/src/main/resources/application-prod.yml
Labels: 2️⃣ Priority: Medium

#35 🔀 :: 실행되지 않는 jar 파일 생성되는 이슈 해결
  buildSrc/src/main/kotlin/PluginVersions.kt
  goms-application/gradle/wrapper/gradle-wrapper.jar
  goms-application/gradle/wrapper/gradle-wrapper.properties
  goms-domain/gradle/wrapper/gradle-wrapper.jar
  goms-domain/gradle/wrapper/gradle-wrapper.properties
  goms-infrastructure/build.gradle.kts
  goms-infrastructure/gradle/wrapper/gradle-wrapper.jar
  goms-infrastructure/gradle/wrapper/gradle-wrapper.properties
  goms-presentation/build.gradle.kts
  goms-presentation/gradle/wrapper/gradle-wrapper.jar
  goms-presentation/gradle/wrapper/gradle-wrapper.properties
Labels: 1️⃣ Priority: High, 😈 버그 fix

#42 MethodArgumentNotValidException 핸들러 수정
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/exception/handler/GlobalExceptionHandler.kt
Labels: 1️⃣ Priority: High, 😈 버그 fix

#44 🔀 :: 블랙리스트 삭제 기능 구현
  goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/DeleteOutingBlacklistUseCase.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/outing/OutingBlackListRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingBlackListRepositoryImpl.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilController.kt
  goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/DeleteOutingBlackListUseCaseTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature, ✅ test

#48 🔀 :: 프로필 반환 기능
  goms-application/src/main/kotlin/com/goms/v2/common/util/AccountUtil.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/account/data/dto/ProfileDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/account/data/dto/StudentNumberDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/QueryAccountProfileUseCase.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/late/LateRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/late/entity/LateJpaEntity.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/late/repository/LateJpaRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/late/repository/LateRepositoryImpl.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/account/AccountController.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/account/dto/response/ProfileHttpResponse.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/account/dto/response/StudentNumHttpResponse.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/account/mapper/AccountDataMapper.kt
  goms-presentation/src/test/kotlin/com/goms/v2/common/AnyValueObjectGenerator.kt
  goms-presentation/src/test/kotlin/com/goms/v2/domain/account/QueryAccountProfileUseCaseTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature, ✅ test

#50 🔀 :: 현재 외출중인 학생 리스트 반환 기능 구현
  buildSrc/src/main/kotlin/AllOpen.kt
  goms-application/build.gradle.kts
  goms-application/src/main/kotlin/com/goms/v2/common/annotation/UseCaseWithReadOnlyTransaction.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/outing/data/dto/OutingAccountDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/outing/usecase/QueryOutingAccountUseCase.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/outing/OutingRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/config/ComponentScanConfig.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/SecurityConfig.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/mapper/OutingMapper.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingJpaRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingRepositoryImpl.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/account/AccountController.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/auth/AuthController.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/email/EmailAuthController.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/OutingController.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/dto/response/OutingAccountHttpResponse.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/mapper/OutingDataMapper.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilController.kt
  goms-presentation/src/test/kotlin/com/goms/v2/domain/outing/QueryOutingAccountUseCaseTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature, ✅ test

#52 🔀 :: 현재 외출중인 학생 카운트 기능 구현
  goms-application/src/main/kotlin/com/goms/v2/domain/outing/usecase/QueryOutingCountUseCase.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/outing/OutingRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingRepositoryImpl.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/OutingController.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/dto/response/OutingCountHttpResponse.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/mapper/OutingDataMapper.kt
  goms-presentation/src/test/kotlin/com/goms/v2/domain/outing/QueryOutingCountUseCaseTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature, ✅ test

#54 🔀 :: 현재 외출중인 학생 검색 기능 구현
  goms-application/src/main/kotlin/com/goms/v2/domain/outing/usecase/SearchOutingAccountUseCase.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/outing/OutingRepository.kt
  goms-infrastructure/build.gradle.kts
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/config/QueryDslConfig.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingJpaRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingRepositoryImpl.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/OutingController.kt
  goms-presentation/src/test/kotlin/com/goms/v2/domain/outing/SearchOutingAccountUseCaseTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature, ✅ test

#56 🔀 :: 외출 가능 시간 검증 기능 구현
  goms-application/src/main/kotlin/com/goms/v2/common/annotation/UseCase.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/outing/usecase/ValidateOutingTimeUseCase.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/config/ComponentScanConfig.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/OutingController.kt
  goms-presentation/src/test/kotlin/com/goms/v2/domain/outing/ValidateOutingTimeUseCaseTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature, ✅ test

#60 🔀 :: 사용자 전체 리스트 기능 구현
  goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/data/dto/AccountDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/QueryAllAccountUseCase.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/account/AccountRepository.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/outing/OutingBlackListRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/repository/AccountRepositoryImpl.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/mapper/OutingBlackListMapper.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingBlackListRepositoryImpl.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingJpaRepository.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilController.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/dto/response/AllAccountHttpResponse.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/mapper/StudentCouncilDataMapper.kt
  goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/QueryAllAccountUseCaseTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature, ✅ test

#64 🔀 :: UseCase 테스트 코드 application 계층으로 이동
  goms-application/src/test/kotlin/com/goms/v2/common/AnyValueObjectGenerator.kt
  goms-application/src/test/kotlin/com/goms/v2/domain/account/QueryAccountProfileUseCaseTest.kt
  goms-application/src/test/kotlin/com/goms/v2/domain/auth/ReissueTokenUseCaseTest.kt
  goms-application/src/test/kotlin/com/goms/v2/domain/late/SaveLateAccountUseCaseTest.kt
  goms-application/src/test/kotlin/com/goms/v2/domain/outing/DeleteOutingStudentsUseCaseTest.kt
  goms-application/src/test/kotlin/com/goms/v2/domain/outing/OutingUseCaseTest.kt
  goms-application/src/test/kotlin/com/goms/v2/domain/outing/QueryOutingAccountUseCaseTest.kt
  goms-application/src/test/kotlin/com/goms/v2/domain/outing/QueryOutingCountUseCaseTest.kt
  goms-application/src/test/kotlin/com/goms/v2/domain/outing/SearchOutingAccountUseCaseTest.kt
  goms-application/src/test/kotlin/com/goms/v2/domain/outing/ValidateOutingTimeUseCaseTest.kt
  goms-application/src/test/kotlin/com/goms/v2/domain/studentCouncil/CreateOutingUseCaseTest.kt
  goms-application/src/test/kotlin/com/goms/v2/domain/studentCouncil/DeleteOutingBlackListUseCaseTest.kt
  goms-application/src/test/kotlin/com/goms/v2/domain/studentCouncil/QueryAllAccountUseCaseTest.kt
  goms-application/src/test/kotlin/com/goms/v2/domain/studentCouncil/SaveOutingBlackListUseCaseTest.kt
  goms-presentation/src/test/kotlin/com/goms/v2/domain/.gitkeep
Labels: 1️⃣ Priority: High, 🔨 코드 리팩터링

#65 🔀 :: 지각생 랭킹 기능 구현
  goms-application/src/main/kotlin/com/goms/v2/domain/late/data/dto/LateRankDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/late/usecase/QueryLateRankUseCase.kt
  goms-application/src/test/kotlin/com/goms/v2/common/AnyValueObjectGenerator.kt
  goms-application/src/test/kotlin/com/goms/v2/domain/late/QueryLateRankUseCaseTest.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/late/LateRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/late/repository/LateRepositoryImpl.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/late/LateController.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/late/dto/LateRankHttpResponse.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/late/mapper/LateDataMapper.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature, ✅ test

#68 🔀 :: 권한 수정 기능 구현
  goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/data/dto/GrantAuthorityDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/GrantAuthorityUseCase.kt
  goms-application/src/test/kotlin/com/goms/v2/domain/studentCouncil/GrantAuthorityUseCaseTest.kt
  goms-domain/src/main/kotlin/com/goms/v2/domain/account/Account.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilController.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/dto/request/GrantAuthorityHttpRequest.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/mapper/StudentCouncilDataMapper.kt
  goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilControllerTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature, ✅ test

#70 🔀 :: 메서드 반환 타입에 변경에 따른 테스트코드 수정
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/SignInUseCase.kt
  goms-application/src/test/kotlin/com/goms/v2/domain/studentCouncil/GrantAuthorityUseCaseTest.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/account/AccountRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/repository/AccountRepositoryImpl.kt
Labels: 1️⃣ Priority: High, 😈 버그 fix

#73 🔀 :: 이메일 인증 관련 기능 구현 & 테스트코드 작성
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/ReissueTokenUseCase.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/email/usecase/SendEmailUseCase.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/email/usecase/VerifyAuthCodeUseCase.kt
  goms-application/src/test/kotlin/com/goms/v2/common/AnyValueObjectGenerator.kt
  goms-application/src/test/kotlin/com/goms/v2/domain/email/SendEmailUseCaseTest.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/email/EmailAuthController.kt
  goms-presentation/src/test/kotlin/com/goms/v2/domain/email/EmailAuthControllerTest.kt
Labels: 1️⃣ Priority: High, ✨ Feature, ✅ test

#76 🔀:: 외출 / 복귀 controller 테스트 코드 작성
  goms-presentation/src/test/kotlin/com/goms/v2/domain/outing/OutingControllerTest.kt
Labels: 2️⃣ Priority: Medium, ✅ test

#78 🔀 :: 외출 현황 리스트 테스트코드 작성
  goms-presentation/src/test/kotlin/com/goms/v2/domain/outing/OutingControllerTest.kt
Labels: 2️⃣ Priority: Medium, ✅ test

#74 🔀 :: 사용자 검색 기능 구현
  goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/data/dto/SearchAccountDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/SearchAccountUseCase.kt
  goms-application/src/test/kotlin/com/goms/v2/domain/studentCouncil/SearchAccountUseCaseTest.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/account/AccountRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/account/repository/AccountRepositoryImpl.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilController.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/mapper/StudentCouncilDataMapper.kt
  goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilControllerTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature, ✅ test

#80 🔀 :: 외출중인 학생 카운트 controller 테스트코드 작성
  goms-presentation/src/test/kotlin/com/goms/v2/domain/outing/OutingControllerTest.kt
Labels: 2️⃣ Priority: Medium, ✅ test

#84 🔀 :: QR 생성 controller 테스트 코드
  goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilControllerTest.kt
Labels: 2️⃣ Priority: Medium, ✅ test

#86 🔀 :: 블랙리스트 전환 controller 테스트 코드
  goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilControllerTest.kt
Labels: 2️⃣ Priority: Medium, ✅ test

#88 🔀 :: 블랙리스트 취소 controller 테스트 코드 추가
  goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilControllerTest.kt
Labels: 2️⃣ Priority: Medium, ✅ test

#82 🔀 :: 외출중인 학생 검색 controller 테스트 코드
  goms-presentation/src/test/kotlin/com/goms/v2/domain/outing/OutingControllerTest.kt
Labels: 2️⃣ Priority: Medium, ✅ test

#91 🔀 :: 사용자 전체 리스트 controller 테스트 코드 추가
  goms-presentation/src/test/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilControllerTest.kt
Labels: 2️⃣ Priority: Medium, ✅ test

#95 🔀 :: 지각 랭킹 확인 controller 테스트 코드 추가
  goms-presentation/src/test/kotlin/com/goms/v2/domain/late/LateControllerTest.kt
Labels: 2️⃣ Priority: Medium, ✅ test

#96 🔀 :: 외출 가능 시간인지 검증 controller 테스트 코드
  goms-presentation/src/test/kotlin/com/goms/v2/domain/outing/OutingControllerTest.kt
Labels: 2️⃣ Priority: Medium, ✅ test

#98 🔀 :: 프로필 반환 controller 테스트코드
  goms-presentation/src/test/kotlin/com/goms/v2/domain/account/AccountControllerTest.kt
Labels: 2️⃣ Priority: Medium, ✅ test

#103 🔀 :: OutingUUIDExpTimeProperties application 계층으로 이동
  goms-application/src/main/kotlin/com/goms/v2/common/property/studentCouncil/OutingUUIDExpTimeProperties.kt
Labels: 2️⃣ Priority: Medium, 🔨 코드 리팩터링

#101 🔀 :: 필요없는 .gitkeep 삭제
  goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/.gitkeep
  goms-application/src/test/kotlin/com/goms/v2/.gitkeep
  goms-presentation/src/main/kotlin/com/goms/v2/.gitkeep
  goms-presentation/src/test/kotlin/com/goms/v2/.gitkeep
Labels: 2️⃣ Priority: Medium, 🔨 코드 리팩터링

#106 🔀 :: profileDto에서 accountIdx 삭제하기
  goms-application/src/main/kotlin/com/goms/v2/domain/account/data/dto/ProfileDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/QueryAccountProfileUseCase.kt
  goms-application/src/test/kotlin/com/goms/v2/domain/account/QueryAccountProfileUseCaseTest.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/account/dto/response/ProfileHttpResponse.kt
  goms-presentation/src/test/kotlin/com/goms/v2/domain/account/AccountControllerTest.kt
Labels: 2️⃣ Priority: Medium, 🔨 코드 리팩터링

#108 🔀 :: return문 말고 = 을 사용해서 반환하기
  goms-application/src/main/kotlin/com/goms/v2/domain/outing/usecase/SearchOutingAccountUseCase.kt
Labels: 2️⃣ Priority: Medium, 🔨 코드 리팩터링

#111 🔀 :: TokenParsePort로 클래스명 변경
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/spi/TokenParsePort.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/ReissueTokenUseCase.kt
  goms-application/src/test/kotlin/com/goms/v2/domain/auth/ReissueTokenUseCaseTest.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/jwt/TokenParserAdapter.kt
Labels: 2️⃣ Priority: Medium, 🔨 코드 리팩터링

#113 🔀 :: OAuthPort로 클래스명 변경
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/data/dto/OAuthTokenDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/data/dto/OAuthUserInfoDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/spi/GAuthPort.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/spi/OAuthPort.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/SignInUseCase.kt
  goms-application/src/test/kotlin/com/goms/v2/domain/auth/SignInUseCaseTest.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/gauth/GAuthAdapter.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/gauth/mapper/GAuthDataMapper.kt
Labels: 2️⃣ Priority: Medium, 🔨 코드 리팩터링

#115 🔀 :: 이메일 전송하기 전에 GOMS 회원인지 검증하기
  goms-application/src/main/kotlin/com/goms/v2/domain/auth/usecase/SendEmailUseCase.kt
Labels: 2️⃣ Priority: Medium, 🔨 코드 리팩터링

#118 🔀:: CloudType CD 스크립트 작성
  .github/workflows/CD-Dev.yml
Labels: 2️⃣ Priority: Medium, ✨ Feature

#120 🔀 :: HealthCheckController 추가
  goms-presentation/src/main/kotlin/com/goms/v2/domain/HealthCheckController.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#122 🔀 :: EmailSenderAdapter 클래스 thirdparty로 이동
  goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/email/EmailSendAdapter.kt
Labels: 3️⃣ Priority: Low, 🔨 코드 리팩터링

#124 🔀 :: 지각자 저장 시간 변경
  goms-application/src/main/kotlin/com/goms/v2/domain/outing/scheduler/OutingScheduler.kt
Labels: 1️⃣ Priority: High, 🔨 코드 리팩터링
