Repository team-haribo/GOMS-Backend-V2, pull requests merged in 2023-09, with the labels that each got.

#125 🔀 :: FCM 알림 기능 추가
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependenciesVersions.kt
  goms-application/src/main/kotlin/com/goms/v2/common/exception/ErrorCode.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/notification/exception/DeviceTokenNotFoundException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/notification/scheduler/NotificationScheduler.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/notification/spi/NotificationPort.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/notification/usecase/SendNotificationUseCase.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/notification/usecase/SetDeviceTokenUseCase.kt
  goms-domain/src/main/kotlin/com/goms/v2/domain/notification/DeviceToken.kt
  goms-domain/src/main/kotlin/com/goms/v2/domain/notification/Notification.kt
  goms-domain/src/main/kotlin/com/goms/v2/domain/notification/NotificationType.kt
  goms-domain/src/main/kotlin/com/goms/v2/domain/notification/Topic.kt
  goms-domain/src/main/kotlin/com/goms/v2/domain/notification/Writer.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/late/LateRepository.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/notification/DeviceTokenRepository.kt
  goms-infrastructure/build.gradle.kts
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/config/PropertiesScanConfig.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/SecurityConfig.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/late/repository/LateJpaRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/late/repository/LateRepositoryImpl.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/notification/entity/DeviceTokenEntity.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/notification/mapper/DeviceTokenMapper.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/notification/repository/DeviceTokenJpaRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/notification/repository/DeviceTokenRepositoryImpl.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/outing/repository/OutingRepositoryImpl.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/notification/FcmAdapter.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/notification/config/FcmConfig.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/thirdparty/notification/property/FcmProperties.kt
  goms-infrastructure/src/main/resources/application-local.yml
  goms-infrastructure/src/main/resources/application-prod.yml
  goms-presentation/src/main/kotlin/com/goms/v2/domain/notification/NotificationController.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#129 🔀 :: timeZone 설정하기
  goms-infrastructure/src/main/kotlin/com/goms/v2/GomsV2Application.kt
Labels: 2️⃣ Priority: Medium, 🔨 코드 리팩터링

#127 🔀 :: CD-Dev 결과 디스코드 알림 Job 추가
  .github/workflows/CD-Dev.yml
Labels: 2️⃣ Priority: Medium, ✨ Feature

#132 boolean 타입 변수 Mapping 오류 수정
  goms-application/src/main/kotlin/com/goms/v2/domain/studentCouncil/usecase/SearchAccountUseCase.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/account/mapper/AccountDataMapper.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/mapper/StudentCouncilDataMapper.kt
Labels: 1️⃣ Priority: High, 😈 버그 fix
