Repository team-haribo/GOMS-Backend-V2, pull requests merged in 2024-03, with the labels that each got.

#205 🔀 :: 비밀번호 정규식 변경
  goms-presentation/src/main/kotlin/com/goms/v2/domain/auth/dto/request/SignUpHttpRequest.kt
Labels: 2️⃣ Priority: Medium, 🔨 코드 리팩터링

#203 🔀 :: 프로필 이미지 삭제 api
  goms-application/src/main/kotlin/com/goms/v2/common/exception/ErrorCode.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/account/exception/ProfileUrlNotExistException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/DeleteImageUseCase.kt
  goms-domain/src/main/kotlin/com/goms/v2/domain/account/Account.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/account/AccountController.kt
  goms-presentation/src/test/kotlin/com/goms/v2/domain/account/AccountControllerTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#207 :: 비밀번호 재설정 api 권한 변경
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/config/SecurityConfig.kt
Labels: 2️⃣ Priority: Medium, 🔨 코드 리팩터링

#211 🔀 :: try-catch 문 추가
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/filter/RequestLogFilter.kt
Labels: 1️⃣ Priority: High, 😈 버그 fix

#213 🔀 :: try-catch 문 삭제
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/filter/RequestLogFilter.kt
Labels: 1️⃣ Priority: High, 😈 버그 fix

#215 #214 device token 삭제하기
  goms-application/src/main/kotlin/com/goms/v2/domain/notification/usecase/DeleteDeviceTokenUseCase.kt
  goms-domain/src/main/kotlin/com/goms/v2/repository/notification/DeviceTokenRepository.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/config/SecurityConfig.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/persistence/notification/repository/DeviceTokenRepositoryImpl.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/notification/NotificationController.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#217 🔀 :: Controller 스코프 함수 변경
  goms-presentation/src/main/kotlin/com/goms/v2/domain/account/AccountController.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/auth/AuthController.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/OutingController.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/studentCouncil/StudentCouncilController.kt
Labels: 2️⃣ Priority: Medium, 🔨 코드 리팩터링
