Repository team-haribo/GOMS-Backend-V2, pull requests merged in 2024-04, with the labels that each got.

#209 🔀 :: 로그인 상태에서 비밀번호 변경
  goms-application/src/main/kotlin/com/goms/v2/domain/account/data/dto/ChangePasswordDto.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/account/exception/PasswordNotMatchException.kt
  goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/ChangePasswordUseCase.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/config/SecurityConfig.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/account/AccountController.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/account/dto/request/ChangePasswordRequest.kt
  goms-presentation/src/main/kotlin/com/goms/v2/domain/account/mapper/AccountDataMapper.kt
  goms-presentation/src/test/kotlin/com/goms/v2/domain/account/AccountControllerTest.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#220 🔀 :: DeleteImage 로직 수정
  goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/DeleteImageUseCase.kt
Labels: 1️⃣ Priority: High

#224 #223 update password exception
  goms-application/src/main/kotlin/com/goms/v2/domain/account/usecase/ChangePasswordUseCase.kt
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/config/SecurityConfig.kt
Labels: 2️⃣ Priority: Medium, 😈 버그 fix

#227 🔀 :: logout api authentication
  .DS_Store
  goms-infrastructure/src/main/kotlin/com/goms/v2/global/security/config/SecurityConfig.kt
  gradle/.DS_Store
Labels: 0️⃣ Priority: Critical, 😈 버그 fix

#229 #228 request param
  goms-presentation/src/main/kotlin/com/goms/v2/domain/outing/OutingController.kt
Labels: 1️⃣ Priority: High
